language: r
cache: packages
pandoc_version: 1.19.2.1
latex: true

before_install:
  - tlmgr install iwona babel-portuges
  - apt-get install -y biber

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
  - chmod +x ./slides-pdf/_build_all.sh

script:
  - cd slides-pdf
  - ./_build_all.sh
  - cd ..
  - ./_build.sh
  - ./_deploy.sh
