language: r
cache: packages
pandoc_version: 1.19.2.1

before_install:
  - tlmgr install texlive-fonts-extra

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
  - chmod +x ./slides-pdf/_build_all.sh

script:
  - ./_build.sh
  - ./_deploy.sh
  - cd slides-pdf && ./_build_all.sh
